2017-04-17 22:39:31,997|MainThread|acestream|error during startup
Traceback (most recent call last):
  File "core.c", line 1598, in 
  File "core.c", line 417, in 
  File "core.c", line 243, in 
  File "acestreamengine\CoreApp.pyo", line 12, in <module>
  File "acestreamengine\CoreApp.pyo", line 10, in __load
  File "core.c", line 146, in 
  File "ACEStream\WebUI\WebUI.pyo", line 18, in <module>
  File "wx\__init__.pyo", line 45, in <module>
  File "wx\_core.pyo", line 4, in <module>
  File "wx\_core_.pyo", line 12, in <module>
  File "wx\_core_.pyo", line 10, in __load
ImportError: DLL load failed: Module not found.
2017-04-17 22:44:27,845|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2017-04-17 22:44:27,845|MainThread|acestream|platform=win32
2017-04-17 22:44:27,845|MainThread|acestream|app=acestream
2017-04-17 22:44:27,845|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2017-04-17 22:44:27,845|MainThread|acestream|use_local_db=True
2017-04-17 22:44:27,845|MainThread|acestream|use_m2crypto=True
2017-04-17 22:44:27,845|MainThread|acestream|enable debug: 0
2017-04-17 22:44:27,845|MainThread|acestream|get_default_api_version: 2
2017-04-17 22:44:27,884|MainThread|acestream.coreapp|state_dir=u'C:\\users\\boone\\AppData\\Roaming\\.ACEStream'
2017-04-17 22:44:27,887|MainThread|acestream.coreapp|cannot load session config, use default
2017-04-17 22:44:33,608|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:49786
2017-04-17 22:44:33,608|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2017-04-17 22:44:33,608|MainThread|acestream.LM|listen on 8621
2017-04-17 22:44:33,609|MainThread|acestream.localdb|No existing database found. Attempting to creating a new database u'C:\\users\\boone\\AppData\\Roaming\\.ACEStream\\sqlite\\torrentstream.sdb'
2017-04-17 22:44:33,634|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
2017-04-17 22:44:38,634|AceStreamCoreThread|acestream.LM|start_multicast: error
Traceback (most recent call last):
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 1041, in start_multicast
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 389, in create_multicast_sockets
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 818, in create_multicast_sockets
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 922, in get_local_ips
gaierror: [Errno 11001] getaddrinfo failed
2017-04-17 22:44:43,642|MainThread|acestream.VideoServer|start: addr= port=6879 allow_remote=0 allow_intranet=1
2017-04-17 22:44:49,806|MainThread|acestream.lang|setting up languages: default=en_EN.lang system=en_US
2017-04-17 22:44:49,828|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:52267
2017-04-17 22:44:50,012|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=63386
2017-04-17 22:44:50,013|Instance2InstanceThread-36|acestream.APIServer|run: ready to receive remote commands on 63386
2017-04-17 22:44:52,036|BGTaskQueueThread-1|acestream.coreapp|set_allow_sleep_mode: allow=0
2017-04-17 22:45:02,164|AceStreamCoreThread|acestream.BT.Connecter.Connecter|got_broadcast: failed to decode payload
Traceback (most recent call last):
  File "core.c", line 3763, in 
  File "ACEStream\Core\BitTornado\bencode.pyo", line 96, in bdecode
ValueError: bad bencoded data
2017-04-17 22:45:10,709|AceStreamCoreThread|acestream.BT.Connecter.Connecter|got_broadcast: failed to decode payload
Traceback (most recent call last):
  File "core.c", line 3763, in 
  File "ACEStream\Core\BitTornado\bencode.pyo", line 96, in bdecode
ValueError: bad bencoded data
2017-04-17 22:45:25,796|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2017-04-17 22:45:25,796|MainThread|acestream|platform=win32
2017-04-17 22:45:25,796|MainThread|acestream|app=acestream
2017-04-17 22:45:25,796|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2017-04-17 22:45:25,796|MainThread|acestream|use_local_db=True
2017-04-17 22:45:25,798|MainThread|acestream|use_m2crypto=True
2017-04-17 22:45:25,798|MainThread|acestream|enable debug: 0
2017-04-17 22:45:25,798|MainThread|acestream|get_default_api_version: 2
2017-04-17 22:45:25,836|MainThread|acestream.coreapp|state_dir=u'C:\\users\\boone\\AppData\\Roaming\\.ACEStream'
2017-04-17 22:45:25,838|MainThread|acestream.coreapp|cannot load session config, use default
2017-04-17 22:45:31,503|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:53240
2017-04-17 22:45:31,503|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2017-04-17 22:45:31,503|MainThread|acestream.LM|listen on 8621
2017-04-17 22:45:31,697|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
2017-04-17 22:45:36,700|AceStreamCoreThread|acestream.LM|start_multicast: error
Traceback (most recent call last):
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 1041, in start_multicast
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 389, in create_multicast_sockets
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 818, in create_multicast_sockets
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 922, in get_local_ips
gaierror: [Errno 11001] getaddrinfo failed
2017-04-17 22:45:41,704|MainThread|acestream.VideoServer|start: addr= port=6879 allow_remote=0 allow_intranet=1
2017-04-17 22:45:47,187|MainThread|acestream.lang|setting up languages: default=en_EN.lang system=en_US
2017-04-17 22:45:47,217|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:50307
2017-04-17 22:45:47,411|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=64147
2017-04-17 22:45:47,413|Instance2InstanceThread-36|acestream.APIServer|run: ready to receive remote commands on 64147
2017-04-17 22:45:48,790|BGTaskQueueThread-1|acestream.coreapp|set_allow_sleep_mode: allow=0
2017-04-17 23:27:18,726|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2017-04-17 23:27:18,726|MainThread|acestream|platform=win32
2017-04-17 23:27:18,726|MainThread|acestream|app=acestream
2017-04-17 23:27:18,726|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2017-04-17 23:27:18,726|MainThread|acestream|use_local_db=True
2017-04-17 23:27:18,726|MainThread|acestream|use_m2crypto=True
2017-04-17 23:27:18,726|MainThread|acestream|enable debug: 0
2017-04-17 23:27:18,727|MainThread|acestream|get_default_api_version: 2
2017-04-17 23:27:18,766|MainThread|acestream.coreapp|state_dir=u'C:\\users\\boone\\AppData\\Roaming\\.ACEStream'
2017-04-17 23:27:18,769|MainThread|acestream.coreapp|cannot load session config, use default
2017-04-17 23:27:24,505|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:63630
2017-04-17 23:27:24,506|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2017-04-17 23:27:24,506|MainThread|acestream.LM|listen on 8621
2017-04-17 23:27:24,516|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
2017-04-17 23:27:29,517|AceStreamCoreThread|acestream.LM|start_multicast: error
Traceback (most recent call last):
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 1041, in start_multicast
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 389, in create_multicast_sockets
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 818, in create_multicast_sockets
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 922, in get_local_ips
gaierror: [Errno 11001] getaddrinfo failed
2017-04-17 23:27:34,526|MainThread|acestream.VideoServer|start: addr= port=6879 allow_remote=0 allow_intranet=1
2017-04-17 23:27:40,040|MainThread|acestream.lang|setting up languages: default=en_EN.lang system=en_US
2017-04-17 23:27:40,073|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:52888
2017-04-17 23:27:41,595|BGTaskQueueThread-1|acestream.coreapp|set_allow_sleep_mode: allow=0
2017-04-17 23:27:41,723|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=49431
2017-04-17 23:27:41,733|Instance2InstanceThread-36|acestream.APIServer|run: ready to receive remote commands on 49431
2018-08-11 04:37:24,213|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2018-08-11 04:37:24,214|MainThread|acestream|platform=win32
2018-08-11 04:37:24,216|MainThread|acestream|app=acestream
2018-08-11 04:37:24,217|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2018-08-11 04:37:24,217|MainThread|acestream|use_local_db=True
2018-08-11 04:37:24,217|MainThread|acestream|use_m2crypto=True
2018-08-11 04:37:24,217|MainThread|acestream|enable debug: 0
2018-08-11 04:37:24,217|MainThread|acestream|get_default_api_version: 2
2018-08-11 04:37:24,312|MainThread|acestream.coreapp|state_dir=u'C:\\users\\cuongle\\AppData\\Roaming\\.ACEStream'
2018-08-11 04:37:24,322|MainThread|acestream.coreapp|cannot load session config, use default
2018-08-11 04:37:25,834|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:60586
2018-08-11 04:37:25,835|MainThread|acestream.SocketHandler.SocketHandler|failed to bind: addrinfo=[2, None, None, None, ('', 8621)]
2018-08-11 04:37:25,835|MainThread|acestream|failed to init app
Traceback (most recent call last):
  File "core.c", line 336, in 
  File "core.c", line 1064, in 
  File "core.c", line 1054, in 
  File "ACEStream\Core\Session.pyo", line 293, in __init__
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 125, in register
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 141, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 450, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 420, in bind
error: [Errno 10048] Windows Error 0x2740
2018-08-11 04:37:40,013|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2018-08-11 04:37:40,013|MainThread|acestream|platform=win32
2018-08-11 04:37:40,013|MainThread|acestream|app=acestream
2018-08-11 04:37:40,013|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2018-08-11 04:37:40,013|MainThread|acestream|use_local_db=True
2018-08-11 04:37:40,013|MainThread|acestream|use_m2crypto=True
2018-08-11 04:37:40,013|MainThread|acestream|enable debug: 0
2018-08-11 04:37:40,015|MainThread|acestream|get_default_api_version: 2
2018-08-11 04:37:40,078|MainThread|acestream.coreapp|state_dir=u'C:\\users\\cuongle\\AppData\\Roaming\\.ACEStream'
2018-08-11 04:37:40,082|MainThread|acestream.coreapp|cannot load session config, use default
2018-08-11 04:37:41,525|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:60514
2018-08-11 04:37:41,526|MainThread|acestream.SocketHandler.SocketHandler|failed to bind: addrinfo=[2, None, None, None, ('', 8621)]
2018-08-11 04:37:41,526|MainThread|acestream|failed to init app
Traceback (most recent call last):
  File "core.c", line 336, in 
  File "core.c", line 1064, in 
  File "core.c", line 1054, in 
  File "ACEStream\Core\Session.pyo", line 293, in __init__
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 125, in register
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 141, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 450, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 420, in bind
error: [Errno 10048] Windows Error 0x2740
2018-08-11 04:37:54,983|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2018-08-11 04:37:54,984|MainThread|acestream|platform=win32
2018-08-11 04:37:54,984|MainThread|acestream|app=acestream
2018-08-11 04:37:54,984|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2018-08-11 04:37:54,984|MainThread|acestream|use_local_db=True
2018-08-11 04:37:54,986|MainThread|acestream|use_m2crypto=True
2018-08-11 04:37:54,986|MainThread|acestream|enable debug: 0
2018-08-11 04:37:54,986|MainThread|acestream|get_default_api_version: 2
2018-08-11 04:37:55,051|MainThread|acestream.coreapp|state_dir=u'C:\\users\\cuongle\\AppData\\Roaming\\.ACEStream'
2018-08-11 04:37:55,055|MainThread|acestream.coreapp|cannot load session config, use default
2018-08-11 04:37:56,595|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:64674
2018-08-11 04:37:56,596|MainThread|acestream.SocketHandler.SocketHandler|failed to bind: addrinfo=[2, None, None, None, ('', 8621)]
2018-08-11 04:37:56,596|MainThread|acestream|failed to init app
Traceback (most recent call last):
  File "core.c", line 336, in 
  File "core.c", line 1064, in 
  File "core.c", line 1054, in 
  File "ACEStream\Core\Session.pyo", line 293, in __init__
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 125, in register
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 141, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 450, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 420, in bind
error: [Errno 10048] Windows Error 0x2740
2018-08-11 04:38:09,517|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2018-08-11 04:38:09,517|MainThread|acestream|platform=win32
2018-08-11 04:38:09,517|MainThread|acestream|app=acestream
2018-08-11 04:38:09,517|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2018-08-11 04:38:09,517|MainThread|acestream|use_local_db=True
2018-08-11 04:38:09,517|MainThread|acestream|use_m2crypto=True
2018-08-11 04:38:09,517|MainThread|acestream|enable debug: 0
2018-08-11 04:38:09,519|MainThread|acestream|get_default_api_version: 2
2018-08-11 04:38:09,573|MainThread|acestream.coreapp|state_dir=u'C:\\users\\cuongle\\AppData\\Roaming\\.ACEStream'
2018-08-11 04:38:09,578|MainThread|acestream.coreapp|cannot load session config, use default
2018-08-11 04:38:10,880|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:51602
2018-08-11 04:38:10,881|MainThread|acestream.SocketHandler.SocketHandler|failed to bind: addrinfo=[2, None, None, None, ('', 8621)]
2018-08-11 04:38:10,881|MainThread|acestream|failed to init app
Traceback (most recent call last):
  File "core.c", line 336, in 
  File "core.c", line 1064, in 
  File "core.c", line 1054, in 
  File "ACEStream\Core\Session.pyo", line 293, in __init__
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 125, in register
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 141, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 450, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 420, in bind
error: [Errno 10048] Windows Error 0x2740
2018-08-11 04:38:23,635|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2018-08-11 04:38:23,637|MainThread|acestream|platform=win32
2018-08-11 04:38:23,637|MainThread|acestream|app=acestream
2018-08-11 04:38:23,637|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2018-08-11 04:38:23,637|MainThread|acestream|use_local_db=True
2018-08-11 04:38:23,637|MainThread|acestream|use_m2crypto=True
2018-08-11 04:38:23,638|MainThread|acestream|enable debug: 0
2018-08-11 04:38:23,638|MainThread|acestream|get_default_api_version: 2
2018-08-11 04:38:23,694|MainThread|acestream.coreapp|state_dir=u'C:\\users\\cuongle\\AppData\\Roaming\\.ACEStream'
2018-08-11 04:38:23,697|MainThread|acestream.coreapp|cannot load session config, use default
2018-08-11 04:38:25,325|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:50171
2018-08-11 04:38:25,328|MainThread|acestream.SocketHandler.SocketHandler|failed to bind: addrinfo=[2, None, None, None, ('', 8621)]
2018-08-11 04:38:25,328|MainThread|acestream|failed to init app
Traceback (most recent call last):
  File "core.c", line 336, in 
  File "core.c", line 1064, in 
  File "core.c", line 1054, in 
  File "ACEStream\Core\Session.pyo", line 293, in __init__
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 125, in register
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 141, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 450, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 420, in bind
error: [Errno 10048] Windows Error 0x2740
2018-08-11 04:38:39,045|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2018-08-11 04:38:39,046|MainThread|acestream|platform=win32
2018-08-11 04:38:39,046|MainThread|acestream|app=acestream
2018-08-11 04:38:39,046|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2018-08-11 04:38:39,046|MainThread|acestream|use_local_db=True
2018-08-11 04:38:39,046|MainThread|acestream|use_m2crypto=True
2018-08-11 04:38:39,046|MainThread|acestream|enable debug: 0
2018-08-11 04:38:39,046|MainThread|acestream|get_default_api_version: 2
2018-08-11 04:38:39,111|MainThread|acestream.coreapp|state_dir=u'C:\\users\\cuongle\\AppData\\Roaming\\.ACEStream'
2018-08-11 04:38:39,115|MainThread|acestream.coreapp|cannot load session config, use default
2018-08-11 04:38:40,585|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:63562
2018-08-11 04:38:40,586|MainThread|acestream.SocketHandler.SocketHandler|failed to bind: addrinfo=[2, None, None, None, ('', 8621)]
2018-08-11 04:38:40,586|MainThread|acestream|failed to init app
Traceback (most recent call last):
  File "core.c", line 336, in 
  File "core.c", line 1064, in 
  File "core.c", line 1054, in 
  File "ACEStream\Core\Session.pyo", line 293, in __init__
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 125, in register
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 141, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 450, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 420, in bind
error: [Errno 10048] Windows Error 0x2740
2018-08-11 04:38:53,395|MainThread|acestream|init segmenter done: log_path=C:\users\boone\Application Data\ACEStream\engine\segmenter.log
2018-08-11 04:38:53,395|MainThread|acestream|platform=win32
2018-08-11 04:38:53,395|MainThread|acestream|app=acestream
2018-08-11 04:38:53,397|MainThread|acestream|version=3.1.16.1 code=3011601 revision=3256 date=2017/02/08 02:11:53
2018-08-11 04:38:53,397|MainThread|acestream|use_local_db=True
2018-08-11 04:38:53,397|MainThread|acestream|use_m2crypto=True
2018-08-11 04:38:53,397|MainThread|acestream|enable debug: 0
2018-08-11 04:38:53,398|MainThread|acestream|get_default_api_version: 2
2018-08-11 04:38:53,460|MainThread|acestream.coreapp|state_dir=u'C:\\users\\cuongle\\AppData\\Roaming\\.ACEStream'
2018-08-11 04:38:53,464|MainThread|acestream.coreapp|cannot load session config, use default
2018-08-11 04:38:54,709|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:52620
2018-08-11 04:38:54,710|MainThread|acestream.SocketHandler.SocketHandler|failed to bind: addrinfo=[2, None, None, None, ('', 8621)]
2018-08-11 04:38:54,710|MainThread|acestream|failed to init app
Traceback (most recent call last):
  File "core.c", line 336, in 
  File "core.c", line 1064, in 
  File "core.c", line 1054, in 
  File "ACEStream\Core\Session.pyo", line 293, in __init__
  File "ACEStream\Core\APIImplementation\LaunchManyCore.pyo", line 125, in register
  File "ACEStream\Core\BitTornado\RawServer.pyo", line 141, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 450, in find_and_bind
  File "ACEStream\Core\BitTornado\SocketHandler.pyo", line 420, in bind
error: [Errno 10048] Windows Error 0x2740
